### ISSUE TITLE
Check if an expression depends on all its input variables

### ISSUE THREAD

**Issue by AlOa** [darioizzo/d-CGP#12]
Hi,
which is the best way to check if an expression depends on all its input variables?
I use CGP to solve some PDE.  Sometimes  the expression does not  depends on all its input variables, but I want that the solution  depends on all the variables. Now I check if the first derivative are zero, if so I add a penalty term. It works ( without it the evolution get stuck in non optimal solutions ) but I don't know if it is the best way.
Thanks
                Alberto

**Comment by darioizzo** [comment]
Indeed to check whether a dCGP expression depends on a variable a call to the derivative is the recommended and most efficient way.

On another note we are currently writing a paper on dCGP including the solving differential equation part, you can checkout our experiments on the notebook at https://github.com/darioizzo/d-CGP/blob/master/examples/solving_odes.ipynb. Its a work in progress so we will update it but it will essentially be part of the tutorials in python.

I am interested on what PDE you are working on. Could you share some details?

**Comment by AlOa** [comment]
> Indeed to check whether a dCGP expression depends on a 
>variable a call to the derivative is the recommended and most 
>efficient way.

OK. I work in c++ because I have some problem with the python interface ( some linking problems, pyaudi works but no d-CGP ). And , to speed up the calculation, I use the gdual_v and to check if a derivative, which is a vectorized_double,  is zero I make a loop on the vector elements. Is that the right way?

>I am interested on what PDE you are working on. 
>Could you share some details?

I tried with the Burgers equation, but without much success, probably I must do more test.
                 Alberto

**Comment by darioizzo** [comment]
gdual_v is indeed way faster in general. good choice.

as for vectorized_double your loop may become inefficient for large number of points, you could maybe check that the symbol is not in the symbol set of the gdual<vectorized_double>? may be faster ... but I guess thats not your bottleneck.

As for the problem, the Burgers equation should be within reach of the dCGP if the boundary conditions are simple enough -> thus an exact solution exists, otherwise you will get approximate solutions.

Let us know if we can help, or if you have comments, feedback on the API.

As per your installation problems, I suggest you to delete all system wide include files / python modules and recheckout the latest versions of audi and dCGP. We changed a lot of file names and if you installed an old version and update this can create messy situations.

**Comment by AlOa** [comment]
> As per your installation problems, I suggest you to delete all system wide include files / python modules and recheckout the latest versions of audi and dCGP

I already done it. The problem is with python_boost, when I import d-CGP it gives a linking error about missing symbols. 
So I work with C++, because I can do the same things. 

> Let us know if we can help, or if you have comments, feedback on the API.

One thing that can be useful, if can be done,  is a function that gives some kind of textual representation of all graph. In python there is a visualization tool, in C++ a text representation  can be used for debug ( hand  setting chromosome as  example ). I'm thinking about something similar to the Theano's computational graph text representation.
Thanks!
                       Alberto

**Comment by darioizzo** [comment]
On boost python, a possible problem is that you have to link manually to the correct boost_python library according on whether you use python2 or python3. In case you hit the problem again, post the exact error message.....
