### ISSUE TITLE
Add constants

### ISSUE THREAD

**Issue by AlOa** [darioizzo/d-CGP#3]
Hi,
I want to add "constants" to the function set. My first guess is to use a function that return a random variables, but the problem is that it return a different values every time  it is called.
There is a way to add constants?

By the way, now the only way to add functions to the function set is using "names". Maybe it is better to add a method to directly add  functions. If you think is a good idea I can make a PR.

Thanks

                  Alberto

**Comment by darioizzo** [comment]
To add constants I would augment the inputs by one and use a constant as input. Not really sure why you want a function that always returns the same constant .... but if you really want, yes you can just add something that always return the same value (put it in a functor and construct it from a constant value)

As for the PR, I did not get your point, how exactly would you want to add a function? Do you have a code example (from the user point of view?)

**Comment by AlOa** [comment]
>To add constants I would augment the inputs by one and use a constant as input
I'm a little confused. If I want to do symbolic regression and the data come from a function like C+x for some C, you say to add some constants to my data and use a levels-back equal to the number of columns? 

For the PR. Suppose a user want to add tanh (or some other simple function that can be used with gdual) to the function set. He write wrappers like that in wrapped_functions.hpp, how can he add this function to a function set?

If I understand the code right, one way to that is something like

function_set basic_set({"sum"});
basic_set().emplace_back(the new basic function, name);

May be a simpler function basic_set.add(the new basic function, name) is more clear.
Thanks!

              Alberto

**Comment by darioizzo** [comment]
In your case I would, after having added in wrapped_functions.hpp the code, modify also function_set.hpp so that you can then write:

function_set my_set("sum", "tanh")

BTW, I am about to push the new versions of AuDi and an update to d-GCP to make it compatible.
So, you will have to reinstall them if you want to use  or make PR to the new versions.

The main difference is on the gdual that is now templated: gdual<double> or, its using version, gdual_d 

In case you do add functions such as tanh, please make PRs on the new code base

**Comment by AlOa** [comment]
Ok, I will wait the new version

**Comment by darioizzo** [comment]
It has been deployed .... let me know if you have problems to understand the new API

**Comment by darioizzo** [comment]
I think that w.r.t. the one you use in the new API you can also specify the function arity.
Soon we will also add weights to connections so that ANN can be encoded and trained.

**Comment by AlOa** [comment]
Ok, thanks

**Comment by AlOa** [comment]
I can't update audi ( and so d-GP ) because I have a little old version of gcc that does not support c++14.  When I will update my Linux distribution, I'll also update to the new version.
Thanks
                      Alberto

**Comment by darioizzo** [comment]
Cool, otherwise I can give you a work around ...

**Comment by AlOa** [comment]
Hi,
is there a work around?

                Alberto

**Comment by darioizzo** [comment]
:) sure .... the only c++14 use is on std::enable_t .. so if you compile using --std=c++11 instead of --std=c++14 and include a new header workaround.hpp with

template< bool B, class T = void >
using std::enable_if_t = typename std::enable_if<B,T>::type;

everything should work again :)

Let me know ...

If its a huge issue for you we could also consider to go back to c++11 since it may be unfair to force the 14 standard for such a small use ...

**Comment by AlOa** [comment]
The 14 standard is supported from gcc 5.2 (with -std=c++14, for older
version is partial supported wuth --std=c++1y), so I think that using it is
no an issue for users.

In my case I can use your work around.

Thanks

                      Alberto

**Comment by bluescarni** [comment]
I would advise to use an ``enable_if_t`` typedef from within audi instead. One is not supposed to add new types to the ``std`` namespace, and that workaround will prevent compilation with a C++14 capable compiler.

**Comment by darioizzo** [comment]
Indeed thats better coding ....

**Comment by darioizzo** [comment]
Closing this as the user reported a successful installation.
